name: Metrics

on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: Orlando161296
          filename: assets/metrics.calendar.svg
          base: ""
          config_timezone: America/Caracas
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Most used languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: Orlando161296
          filename: assets/metrics.languages.svg
          base: ""
          config_timezone: America/Caracas
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_ignored: html, css

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: Orlando161296
          filename: assets/metrics.achievements.svg
          base: ""
          config_timezone: America/Caracas
          plugin_achievements: yes
          plugin_achievements_display: compact
